<a href="https://colab.research.google.com/github/akshaya16-cell/Netflix-data-analysis-Project/blob/main/minor_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('Data set for DADS June.csv')
df

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962
...,...,...,...,...,...,...,...,...
1323,2024-06-30,11:53,SWIGGY-INSTAMART,DR,637.00,-311783.0,UPI,TXN274261
1324,30 Jun 2024,16:35,BHIM ZEPTO,DR,693.00,-312476.0,UPI,TXN792601
1325,30/06/24,17:12,UPI-STARBUCKS@AXIS,DR,327.00,-310557.0,UPI,TXN859233
1326,2024-06-30,19:56,POS ZOMATO,DR,₹589,-311146.0,UPI,TXN492729
1327,30/06/24,22:27,OLA ELECTRIC,DR,₹208,-312684.0,UPI,TXN910085

In [ ]:
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [ ]:
df.tail()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
1323,2024-06-30,11:53,SWIGGY-INSTAMART,DR,637.00,-311783.0,UPI,TXN274261
1324,30 Jun 2024,16:35,BHIM ZEPTO,DR,693.00,-312476.0,UPI,TXN792601
1325,30/06/24,17:12,UPI-STARBUCKS@AXIS,DR,327.00,-310557.0,UPI,TXN859233
1326,2024-06-30,19:56,POS ZOMATO,DR,₹589,-311146.0,UPI,TXN492729
1327,30/06/24,22:27,OLA ELECTRIC,DR,₹208,-312684.0,UPI,TXN910085

In [ ]:
df.isnull().sum()

Date           0
Time           0
Description    0
Type           0
Amount         0
Balance        0
Mode           0
Ref            0
dtype: int64

In [ ]:
df.shape

(1328, 8)

In [ ]:
df.columns

Index(['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode',
       'Ref'],
      dtype='object')

In [ ]:
df.duplicated().sum()

np.int64(18)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(1310, 8)

In [ ]:
df["Date"] = pd.to_datetime(
    df["Date"],
    dayfirst=True,
    errors="coerce"
)

/tmp/ipykernel_358/459013217.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date"] = pd.to_datetime(

In [ ]:
df["Date"].isnull().sum()

np.int64(1167)

In [ ]:
df['Description'].unique()

array(['AMAZON SELLER SVCS', 'BHIM-BMTC',
       'NEFT-TECHCRUSH LABS-SALARY MAY24', 'UPI-AMAN-8934@OKAXIS',
       'BHIM-BLINKIT', 'BHIM ZEPTO', 'UPI-UBER-2426@HDFCBANK',
       'POS SWIGGY BANGALORE', 'UPI-GROWWPAY@HDFCBANK', 'OLA ELECTRIC',
       'BMS MOVIE TICKETS', 'POS OLA-PRIME', 'SWIGGY-INSTAMART',
       'UPI-STARBUCKS@AXIS', 'UPI-THIRDWAVE@OKAXIS', 'ANI Technologies',
       'BMTC BUS PASS', 'POS TRUFFLES', 'FLIPKART INDIA',
       'POS SWIGGY-RESTAURANT', 'GROFERS INDIA P L', 'POS UBER BANGALORE',
       'BANGALORE ELEC SUPPLY', 'TWC INDIA', 'UPI-BESCOM-BILL@HDFCBANK',
       'UPI-AMAN-0816@OKAXIS', 'ROPPEN TRANSPORTATION', 'OLA CABS',
       'POS ZOMATO', 'UPI-AMAZONPAY@HDFCBANK', 'POS BLINKIT',
       'IMPS-RENT-LANDLORD-75500265', 'ZOMATO MEDIA P L',
       'UPI-ANKIT-6430@OKAXIS', 'UPI-OLACABS@HDFCBANK',
       'UPI-JIORECHARGE@PAYTM', 'UPI-CCD@HDFCBANK', 'Swiggy*Order',
       'INSTAMART BANGALORE', 'UPI-ZOMATO-LIMITED@PAYTM',
       'AVENUE SUPERMARTS', 'POS HP PETROL STATION',
       'UPI-VIKAS-6060@OKAXIS', 'POS BANGALORE RESTAURANT',
       'UPI-ZERODHA-COIN@AXIS', 'BHIM SWIGGY', 'UPI-BOOKMYSHOW@HDFCBANK',
       'BLINKIT BANGALORE', 'POS ZEPTO BANGALORE', 'UPI-DMART@OKAXIS',
       'UPI-RAPIDO@OKAXIS', 'BUNDL Tech P L', 'TATA STARBUCKS',
       'POS CAFE COFFEE DAY', 'UBER SYSTEMS INDIA', 'UPI-MYNTRA@HDFCBANK',
       'UPI-FLIPKART@HDFCBANK', 'UPI-BWSSB@AXIS',
       'UPI-ZOMATO6393@OKICICI', 'AMAZON IN', 'UPI-NETFLIX-MEMB@HDFCBANK',
       'AIRTEL POSTPAID', 'Amazon Pay India', 'UPI-PRIYA-2221@OKAXIS',
       'POS FLIPKART BANGALORE', 'POS NYKAA BANGALORE', 'VI POSTPAID',
       'UPI-UBER-6457@HDFCBANK', 'POS BPCL PETROL PUMP', 'TUMMOC-BMTC',
       'POS INDIAN OIL BANGALORE', 'UPI-SPOTIFY-IN@AXIS', 'POS DINEOUT',
       'UPI-BLINKIT-0656@PAYTM', 'UPI-SWIGGY5057@OKAXIS', 'ZOMATO-DINING',
       'COFFEE DAY GLOBAL', 'UPI-NYKAA@AXIS', 'UPI-SWIGGY9672@OKAXIS',
       'RAPIDO BIKE TAXI', 'UPI-SWIGGY-6560@HDFCBANK', 'DISNEY HOTSTAR',
       'NEFT ZERODHA BROKING', 'UBER INDIA', 'AMAZONIN MARKETPLACE',
       'UPI-ZOMATO4674@OKICICI', 'POS EMPIRE RESTAURANT',
       'ATM-WDL-SBI-5715', 'UPI-SWIGGY-9474@HDFCBANK',
       'POS MEGHANA FOODS', 'ZEPTO MARKETPLACE', 'UPI-IOC9075@HDFCBANK',
       'UPI-SWIGGY-2954@HDFCBANK', 'FKART INTRNET',
       'UPI-SWIGGY-5808@HDFCBANK', 'UPI-BIGBASKET@HDFCBANK',
       'AMZN-INTPYMT', 'AMZN PRIME', 'MYNTRA-ORDER',
       'UPI-SWIGGY-5551@HDFCBANK', 'BUNDL TECH-INSTAMART',
       'MYNTRA DESIGNS', 'POS MYNTRA', 'POS DMART BANGALORE',
       'BIGBASKET BANGALORE', 'POS THIRD WAVE COFFEE', 'SPOTIFY INDIA',
       'UPI-SWIGGY-7959@HDFCBANK', 'UPI-BLINKIT-3798@PAYTM',
       'UPI-BLINKIT-3397@PAYTM', 'UPI-SWIGGY-INSTAMART@OKAXIS',
       'ZOMATO BENGALURU', 'BESCOM ELEC BILL',
       'IMPS-RENT-LANDLORD-39598076', 'UPI-RESTAURANT-7285@PAYTM',
       'POS STARBUCKS BANGALORE', 'UPI-SWIGGY2461@OKAXIS',
       'UPI-SWIGGY4619@OKAXIS', 'IMPS ZERODHA-COIN',
       'UPI-SWIGGY3675@OKAXIS', 'RELIANCE JIO',
       'UPI-SWIGGY-1309@HDFCBANK', 'NETFLIX ENTERTAINMENT',
       'UPI-UBER-5667@HDFCBANK', 'FSN E-COMMERCE',
       'UPI-BLINKIT-2630@PAYTM', 'UPI-RESTAURANT-7678@PAYTM',
       'ATM-WDL-HDFC-4942', 'Uber*Trip', 'UPI-SWIGGY1616@OKAXIS',
       'UPI-NEHA-9795@OKAXIS', 'BIGTREE ENTERTAINMENT',
       'UPI-ZOMATO4177@OKICICI', 'INNOVATIVE RETAIL', 'POS INSTAMART',
       'UPI-RESTAURANT-3715@PAYTM', 'UPI-UBER-1232@HDFCBANK',
       'STAR INDIA PVT LTD', 'UPI-SWIGGY-5933@HDFCBANK',
       'UPI-RESTAURANT-0251@PAYTM', 'UPI-ZOMATO3977@OKICICI',
       'UPI-BLINKIT-7138@PAYTM', 'UPI-SWIGGY8086@OKAXIS',
       'UPI-SWIGGY-6605@HDFCBANK', 'AMAZON PRIME VIDEO',
       'UPI-SWIGGY-7844@HDFCBANK', 'UPI-SWIGGY-1487@HDFCBANK',
       'UPI-UBER-6248@HDFCBANK', 'UPI-NEHA-5906@OKAXIS',
       'KIRANAKART TECH', 'UPI-SWIGGY-7642@HDFCBANK',
       'UPI-ZEPTO-4547@HDFCBANK', 'UPI-ZEPTO-4563@HDFCBANK',
       'IMPS-RENT-LANDLORD-51148088', 'UPI-RESTAURANT-6377@PAYTM',
       'UPI-ZEPTO-3309@HDFCBANK', 'UPI-ZEPTO-0070@HDFCBANK',
       'UPI-SWIGGY-8169@HDFCBANK', 'UPI-VIKAS-5416@OKAXIS',
       'UPI-HOTSTAR@AXIS', 'ATM-WDL-HDFC-9140', 'UPI-ZOMATO6436@OKICICI',
       'ATM-WDL-SBI-4080', 'NETFLIX.COM', 'UPI-IOC0494@HDFCBANK',
       'UPI-RESTAURANT-4630@PAYTM', 'UPI-IOC1246@HDFCBANK',
       'Flipkart Internet', 'UPI-SWIGGY1600@OKAXIS',
       'UPI-SWIGGY8576@OKAXIS', 'ATM-WDL-HDFC-8030', 'SPOTIFY*PREMIUM',
       'UPI-BLINKIT-6907@PAYTM', 'BWSSB WATER BILL',
       'UPI-RESTAURANT-7888@PAYTM', 'GROWW INVEST TECH',
       'UPI-IOC2000@HDFCBANK', 'UPI-SWIGGY5466@OKAXIS',
       'UPI-SNEHA-0942@OKAXIS', 'UPI-SWIGGY-2664@HDFCBANK', 'JIOFIBER',
       'BHARTI AIRTEL LTD', 'UPI-UBER-0377@HDFCBANK',
       'UPI-UBER-5112@HDFCBANK', 'UPI-ZOMATO1274@OKICICI',
       'UPI-SWIGGY4144@OKAXIS', 'UPI-VI-RECHARGE@HDFCBANK',
       'UPI-KARAN-5789@OKAXIS', 'UPI-BLINKIT-1501@PAYTM',
       'ZERODHA-MF SIP', 'UPI-SWIGGY-9575@HDFCBANK',
       'UPI-RESTAURANT-0753@PAYTM', 'NEXTBILLION-GROWW',
       'UPI-ZOMATO5010@OKICICI', 'UPI-BLINKIT-1469@PAYTM',
       'UPI-SWIGGY9328@OKAXIS', 'NYKAA E-RETAIL', 'ATM-WDL-HDFC-3609',
       'UPI-SWIGGY0226@OKAXIS', 'UPI-SWIGGY9600@OKAXIS',
       'IMPS-RENT-LANDLORD-36852906', 'UPI-ZOMATO7344@OKICICI',
       'UPI-ZEPTO-9191@HDFCBANK', 'UPI-ZOMATO9481@OKICICI',
       'UPI-IOC2115@HDFCBANK', 'UPI-SWIGGY-3513@HDFCBANK',
       'UPI-RESTAURANT-3549@PAYTM', 'UPI-PRIYA-8750@OKAXIS',
       'UPI-ZOMATO5845@OKICICI', 'UPI-ZEPTO-6004@HDFCBANK',
       'UPI-BLINKIT-3223@PAYTM', 'UPI-SWIGGY1998@OKAXIS',
       'ATM-WDL-ICICI-6478', 'UPI-SWIGGY0250@OKAXIS',
       'UPI-RESTAURANT-5630@PAYTM', 'UPI-SWIGGY0894@OKAXIS',
       'UPI-ANKIT-9877@OKAXIS', 'UPI-SWIGGY6412@OKAXIS',
       'UPI-SWIGGY-1791@HDFCBANK', 'UPI-SWIGGY5867@OKAXIS',
       'UPI-UBER-8525@HDFCBANK', 'UPI-SWIGGY-4758@HDFCBANK',
       'UPI-BLINKIT-1165@PAYTM', 'UPI-SWIGGY4389@OKAXIS',
       'ATM-WDL-SBI-0237', 'IMPS-RENT-LANDLORD-49966195',
       'UPI-SWIGGY8720@OKAXIS', 'UPI-PRIYA-0104@OKAXIS',
       'UPI-RESTAURANT-8932@PAYTM', 'UPI-SWIGGY9756@OKAXIS',
       'UPI-SWIGGY-1714@HDFCBANK', 'VODAFONE IDEA LTD',
       'ATM-WDL-SBI-0279', 'UPI-SWIGGY-6024@HDFCBANK',
       'UPI-ZEPTO-2913@HDFCBANK', 'UPI-ZOMATO5406@OKICICI',
       'UPI-RESTAURANT-3964@PAYTM', 'UPI-SWIGGY5737@OKAXIS',
       'ATM-WDL-HDFC-8253', 'ZERODHA SECURITIES',
       'UPI-AMAZON-PRIME@HDFCBANK', 'UPI-UBER-4781@HDFCBANK',
       'UPI-RESTAURANT-5691@PAYTM', 'UPI-SWIGGY2847@OKAXIS',
       'UPI-ZOMATO9682@OKICICI', 'UPI-IOC5182@HDFCBANK',
       'UPI-ANKIT-5946@OKAXIS', 'UPI-SWIGGY9088@OKAXIS',
       'UPI-UBER-1392@HDFCBANK', 'UPI-SWIGGY9983@OKAXIS',
       'UPI-ZEPTO-1050@HDFCBANK', 'UPI-ANKIT-1837@OKAXIS',
       'IMPS-RENT-LANDLORD-35126704', 'UPI-SWIGGY8392@OKAXIS',
       'UPI-ZOMATO5117@OKICICI', 'UPI-ZOMATO4622@OKICICI',
       'UPI-SWIGGY1418@OKAXIS', 'ATM-WDL-ICICI-9135',
       'UPI-RESTAURANT-5531@PAYTM', 'UPI-ANKIT-6092@OKAXIS',
       'UPI-SWIGGY7538@OKAXIS', 'ATM-WDL-ICICI-4172',
       'UPI-ZEPTO-5207@HDFCBANK', 'ATM-WDL-SBI-4084',
       'UPI-ZEPTO-7106@HDFCBANK', 'ATM-WDL-ICICI-4739',
       'UPI-SWIGGY6053@OKAXIS', 'UPI-SWIGGY-3505@HDFCBANK',
       'UPI-SWIGGY-0015@HDFCBANK', 'UPI-RESTAURANT-2648@PAYTM',
       'ATM-WDL-SBI-0874', 'UPI-VIKAS-1878@OKAXIS',
       'UPI-SWIGGY6013@OKAXIS', 'UPI-SWIGGY-8838@HDFCBANK',
       'UPI-VIKAS-9964@OKAXIS', 'UPI-RESTAURANT-7645@PAYTM',
       'ATM-WDL-ICICI-3918', 'UPI-SWIGGY-9077@HDFCBANK',
       'UPI-RESTAURANT-0874@PAYTM', 'ATM-WDL-ICICI-5025',
       'UPI-SWIGGY3466@OKAXIS', 'UPI-BLINKIT-1828@PAYTM',
       'UPI-UBER-3218@HDFCBANK'], dtype=object)

In [ ]:
vendor_dict = {
    "Swiggy": ["SWIGGY", "BUNDL"],
    "Zomato": [ "ZOMATO"],
    "Zepto": [ "ZEPTO" ],
    "Amazon": [
        "AMAZON",
        "AMZN",
        "AMAZONPAY"  ],
    "Blinkit": [ "BLINKIT"  ],
    "BigBasket": [ "BIGBASKET" ],
    "Uber": ["UBER"],
    "Ola": ["OLA"],
    "Rapido": [ "RAPIDO" ],
    "BookMyShow": [ "BOOKMYSHOW"],
    "Netflix": [ "NETFLIX"],
    "Spotify": [ "SPOTIFY" ],
    "Hotstar": [ "HOTSTAR","DISNEY"],
    "Jio": ["JIO"],
    "Airtel": ["AIRTEL"],
    "Myntra": ["MYNTRA"],
    "Flipkart": [ "FLIPKART"],
    "Zerodha": ["ZERODHA"]

}

In [ ]:
def extract_vendor(description):

    description = str(description).upper()

    for vendor, keywords in vendor_dict.items():

        for keyword in keywords:

            if keyword in description:
                return vendor

    return "Uncategorised"

In [ ]:
df["vendor_clean"] = df["Description"].apply(extract_vendor)

In [ ]:
df[["Description", "vendor_clean"]].head(10)

                        Description   vendor_clean
0                AMAZON SELLER SVCS         Amazon
1                         BHIM-BMTC  Uncategorised
2  NEFT-TECHCRUSH LABS-SALARY MAY24  Uncategorised
3              UPI-AMAN-8934@OKAXIS  Uncategorised
4                      BHIM-BLINKIT        Blinkit
5                        BHIM ZEPTO          Zepto
6            UPI-UBER-2426@HDFCBANK           Uber
7                      BHIM-BLINKIT        Blinkit
8              POS SWIGGY BANGALORE         Swiggy
9             UPI-GROWWPAY@HDFCBANK  Uncategorised

In [ ]:
print("Unique Vendors:", df["vendor_clean"].nunique())

Unique Vendors: 19

In [ ]:
df[df["vendor_clean"]=="Uncategorised"]["Description"].value_counts().head(50)

Description
ANI Technologies                    18
UPI-STARBUCKS@AXIS                  17
INSTAMART BANGALORE                 16
GROFERS INDIA P L                   15
TUMMOC-BMTC                         14
ROPPEN TRANSPORTATION               14
POS EMPIRE RESTAURANT               13
POS STARBUCKS BANGALORE             13
KIRANAKART TECH                     13
BMTC BUS PASS                       12
POS MEGHANA FOODS                   12
POS BANGALORE RESTAURANT            12
TATA STARBUCKS                      12
POS NYKAA BANGALORE                 11
UPI-THIRDWAVE@OKAXIS                11
POS THIRD WAVE COFFEE               11
POS INDIAN OIL BANGALORE            11
BHIM-BMTC                           11
COFFEE DAY GLOBAL                   11
AVENUE SUPERMARTS                   10
POS DINEOUT                         10
POS TRUFFLES                         9
UPI-CCD@HDFCBANK                     9
UPI-DMART@OKAXIS                     9
POS HP PETROL STATION                9
TWC INDIA                            9
INNOVATIVE RETAIL                    8
BMS MOVIE TICKETS                    7
POS CAFE COFFEE DAY                  6
BANGALORE ELEC SUPPLY                6
UPI-GROWWPAY@HDFCBANK                6
NEFT-TECHCRUSH LABS-SALARY MAY24     6
BESCOM ELEC BILL                     5
BWSSB WATER BILL                     5
POS INSTAMART                        4
UPI-BESCOM-BILL@HDFCBANK             4
FKART INTRNET                        4
UPI-BWSSB@AXIS                       3
VI POSTPAID                          3
POS DMART BANGALORE                  3
UPI-NYKAA@AXIS                       3
FSN E-COMMERCE                       3
STAR INDIA PVT LTD                   3
UPI-VI-RECHARGE@HDFCBANK             3
NEXTBILLION-GROWW                    2
BIGTREE ENTERTAINMENT                2
POS BPCL PETROL PUMP                 2
NYKAA E-RETAIL                       2
VODAFONE IDEA LTD                    2
IMPS-RENT-LANDLORD-75500265          1
Name: count, dtype: int64

In [ ]:
df[df["vendor_clean"]=="Uncategorised"]["Description"].unique()

array(['BHIM-BMTC', 'NEFT-TECHCRUSH LABS-SALARY MAY24',
       'UPI-AMAN-8934@OKAXIS', 'UPI-GROWWPAY@HDFCBANK',
       'BMS MOVIE TICKETS', 'UPI-STARBUCKS@AXIS', 'UPI-THIRDWAVE@OKAXIS',
       'ANI Technologies', 'BMTC BUS PASS', 'POS TRUFFLES',
       'GROFERS INDIA P L', 'BANGALORE ELEC SUPPLY', 'TWC INDIA',
       'UPI-BESCOM-BILL@HDFCBANK', 'UPI-AMAN-0816@OKAXIS',
       'ROPPEN TRANSPORTATION', 'IMPS-RENT-LANDLORD-75500265',
       'UPI-ANKIT-6430@OKAXIS', 'UPI-CCD@HDFCBANK', 'INSTAMART BANGALORE',
       'AVENUE SUPERMARTS', 'POS HP PETROL STATION',
       'UPI-VIKAS-6060@OKAXIS', 'POS BANGALORE RESTAURANT',
       'UPI-DMART@OKAXIS', 'TATA STARBUCKS', 'POS CAFE COFFEE DAY',
       'UPI-BWSSB@AXIS', 'UPI-PRIYA-2221@OKAXIS', 'POS NYKAA BANGALORE',
       'VI POSTPAID', 'POS BPCL PETROL PUMP', 'TUMMOC-BMTC',
       'POS INDIAN OIL BANGALORE', 'POS DINEOUT', 'COFFEE DAY GLOBAL',
       'UPI-NYKAA@AXIS', 'POS EMPIRE RESTAURANT', 'ATM-WDL-SBI-5715',
       'POS MEGHANA FOODS', 'UPI-IOC9075@HDFCBANK', 'FKART INTRNET',
       'POS DMART BANGALORE', 'POS THIRD WAVE COFFEE', 'BESCOM ELEC BILL',
       'IMPS-RENT-LANDLORD-39598076', 'UPI-RESTAURANT-7285@PAYTM',
       'POS STARBUCKS BANGALORE', 'FSN E-COMMERCE',
       'UPI-RESTAURANT-7678@PAYTM', 'ATM-WDL-HDFC-4942',
       'UPI-NEHA-9795@OKAXIS', 'BIGTREE ENTERTAINMENT',
       'INNOVATIVE RETAIL', 'POS INSTAMART', 'UPI-RESTAURANT-3715@PAYTM',
       'STAR INDIA PVT LTD', 'UPI-RESTAURANT-0251@PAYTM',
       'UPI-NEHA-5906@OKAXIS', 'KIRANAKART TECH',
       'IMPS-RENT-LANDLORD-51148088', 'UPI-RESTAURANT-6377@PAYTM',
       'UPI-VIKAS-5416@OKAXIS', 'ATM-WDL-HDFC-9140', 'ATM-WDL-SBI-4080',
       'UPI-IOC0494@HDFCBANK', 'UPI-RESTAURANT-4630@PAYTM',
       'UPI-IOC1246@HDFCBANK', 'ATM-WDL-HDFC-8030', 'BWSSB WATER BILL',
       'UPI-RESTAURANT-7888@PAYTM', 'GROWW INVEST TECH',
       'UPI-IOC2000@HDFCBANK', 'UPI-SNEHA-0942@OKAXIS',
       'UPI-VI-RECHARGE@HDFCBANK', 'UPI-KARAN-5789@OKAXIS',
       'UPI-RESTAURANT-0753@PAYTM', 'NEXTBILLION-GROWW', 'NYKAA E-RETAIL',
       'ATM-WDL-HDFC-3609', 'IMPS-RENT-LANDLORD-36852906',
       'UPI-IOC2115@HDFCBANK', 'UPI-RESTAURANT-3549@PAYTM',
       'UPI-PRIYA-8750@OKAXIS', 'ATM-WDL-ICICI-6478',
       'UPI-RESTAURANT-5630@PAYTM', 'UPI-ANKIT-9877@OKAXIS',
       'ATM-WDL-SBI-0237', 'IMPS-RENT-LANDLORD-49966195',
       'UPI-PRIYA-0104@OKAXIS', 'UPI-RESTAURANT-8932@PAYTM',
       'VODAFONE IDEA LTD', 'ATM-WDL-SBI-0279',
       'UPI-RESTAURANT-3964@PAYTM', 'ATM-WDL-HDFC-8253',
       'UPI-RESTAURANT-5691@PAYTM', 'UPI-IOC5182@HDFCBANK',
       'UPI-ANKIT-5946@OKAXIS', 'UPI-ANKIT-1837@OKAXIS',
       'IMPS-RENT-LANDLORD-35126704', 'ATM-WDL-ICICI-9135',
       'UPI-RESTAURANT-5531@PAYTM', 'UPI-ANKIT-6092@OKAXIS',
       'ATM-WDL-ICICI-4172', 'ATM-WDL-SBI-4084', 'ATM-WDL-ICICI-4739',
       'UPI-RESTAURANT-2648@PAYTM', 'ATM-WDL-SBI-0874',
       'UPI-VIKAS-1878@OKAXIS', 'UPI-VIKAS-9964@OKAXIS',
       'UPI-RESTAURANT-7645@PAYTM', 'ATM-WDL-ICICI-3918',
       'UPI-RESTAURANT-0874@PAYTM', 'ATM-WDL-ICICI-5025'], dtype=object)

In [ ]:

vendor_dict.update({

    # Salary
    "Salary": ["SALARY", "TECHCRUSH LABS"],

    # BMTC
    "BMTC": ["BMTC", "TUMMOC"],

    # Groww
    "Groww": ["GROWW", "GROWWPAY", "NEXTBILLION"],

    # BookMyShow
    "BookMyShow": ["BMS", "BIGTREE"],

    # Starbucks
    "Starbucks": ["STARBUCKS", "TATA STARBUCKS"],

    # Third Wave Coffee
    "Third Wave": ["THIRDWAVE", "THIRD WAVE", "TWC INDIA"],

    # Uber
    "Uber": ["ANI TECHNOLOGIES"],

    # Rapido
    "Rapido": ["ROPPEN"],

    # Restaurants
    "Restaurant": [
        "RESTAURANT",
        "TRUFFLES",
        "EMPIRE",
        "MEGHANA",
        "DINEOUT"
    ],

    # Groceries
    "Blinkit": ["GROFERS"],
    "Instamart": ["INSTAMART"],
    "Dmart": ["DMART", "AVENUE SUPERMARTS"],
    "BigBasket": ["INNOVATIVE RETAIL"],

    # Utilities
    "BESCOM": [
        "BESCOM",
        "BANGALORE ELEC SUPPLY"
    ],

    "BWSSB": [
        "BWSSB",
        "WATER BILL"
    ],

    # Fuel
    "Indian Oil": [
        "IOC",
        "INDIAN OIL"
    ],

    "HP": [
        "HP PETROL"
    ],

    "BPCL": [
        "BPCL"
    ],

    # Cafe
    "Cafe Coffee Day": [
        "CCD",
        "CAFE COFFEE DAY",
        "COFFEE DAY GLOBAL"
    ],

    # Nykaa
    "Nykaa": [
        "NYKAA",
        "FSN E-COMMERCE"
    ],

    # Vodafone Idea
    "VI": [
        "VI POSTPAID",
        "VODAFONE IDEA",
        "UPI-VI"
    ],

    # Entertainment
    "Hotstar": [
        "STAR INDIA"
    ],

    # Rent
    "Rent": [
        "RENT-LANDLORD"
    ],

    # Cash Withdrawal
    "Cash Withdrawal": [
        "ATM-WDL"
    ],

    # P2P Transfers
    "P2P Transfer": [
        "AMAN",
        "ANKIT",
        "PRIYA",
        "NEHA",
        "VIKAS",
        "SNEHA",
        "KARAN"
    ]

})

In [ ]:
df["vendor_clean"] = df["Description"].apply(extract_vendor)

In [ ]:
print(df["vendor_clean"].value_counts().head(20))

vendor_clean
Swiggy             223
Uncategorised      194
Zomato             121
Amazon              86
Restaurant          73
Ola                 69
Zepto               58
Flipkart            43
Starbucks           42
BMTC                37
Third Wave          31
Cafe Coffee Day     26
Dmart               22
Instamart           20
Myntra              20
Nykaa               19
Uber                18
Indian Oil          17
Cash Withdrawal     17
Blinkit             15
Name: count, dtype: int64

In [ ]:
print(df[df["vendor_clean"]=="Uncategorised"]["Description"].unique())

['BHIM-BLINKIT' 'UPI-UBER-2426@HDFCBANK' 'POS UBER BANGALORE'
 'POS BLINKIT' 'UPI-BOOKMYSHOW@HDFCBANK' 'BLINKIT BANGALORE'
 'UPI-RAPIDO@OKAXIS' 'UBER SYSTEMS INDIA' 'UPI-UBER-6457@HDFCBANK'
 'UPI-BLINKIT-0656@PAYTM' 'RAPIDO BIKE TAXI' 'DISNEY HOTSTAR' 'UBER INDIA'
 'FKART INTRNET' 'UPI-BIGBASKET@HDFCBANK' 'BIGBASKET BANGALORE'
 'UPI-BLINKIT-3798@PAYTM' 'UPI-BLINKIT-3397@PAYTM'
 'UPI-UBER-5667@HDFCBANK' 'UPI-BLINKIT-2630@PAYTM' 'Uber*Trip'
 'UPI-UBER-1232@HDFCBANK' 'UPI-BLINKIT-7138@PAYTM'
 'UPI-UBER-6248@HDFCBANK' 'KIRANAKART TECH' 'UPI-HOTSTAR@AXIS'
 'UPI-BLINKIT-6907@PAYTM' 'UPI-UBER-0377@HDFCBANK'
 'UPI-UBER-5112@HDFCBANK' 'UPI-BLINKIT-1501@PAYTM'
 'UPI-BLINKIT-1469@PAYTM' 'UPI-BLINKIT-3223@PAYTM'
 'UPI-UBER-8525@HDFCBANK' 'UPI-BLINKIT-1165@PAYTM'
 'UPI-UBER-4781@HDFCBANK' 'UPI-UBER-1392@HDFCBANK'
 'UPI-BLINKIT-1828@PAYTM' 'UPI-UBER-3218@HDFCBANK']

In [ ]:
df["category"] = df["vendor_clean"].map(category_dict)

In [ ]:
df["category"] = df["category"].fillna("Others")

In [ ]:
print(df["category"].value_counts())

category
Others               413
Food Delivery        344
E-Commerce           149
Transport            101
Quick Commerce        93
Cafe                  73
Utilities             27
Fuel                  26
Investments           23
Subscriptions         21
Cash Withdrawal       17
Personal Transfer     14
Entertainment          9
Name: count, dtype: int64

In [ ]:
total_credits = df[df["Type"] == "credit"]["Amount"].sum()

print(f"Total Credits : ₹{total_credits:,.2f}")

Total Credits : ₹0.00

In [ ]:
total_debits = df[df["Type"] == "debit"]["Amount"].sum()

print(f"Total Debits : ₹{total_debits:,.2f}")

Total Debits : ₹0.00

In [ ]:
net_savings = total_credits - total_debits

print(f"Net Savings : ₹{net_savings:,.2f}")

Net Savings : ₹0.00

In [ ]:
savings_rate = (net_savings / total_credits) * 100

print(f"Savings Rate : {savings_rate:.2f}%")

Savings Rate : nan%

/tmp/ipykernel_358/1414065388.py:1: RuntimeWarning: invalid value encountered in scalar divide
  savings_rate = (net_savings / total_credits) * 100

In [ ]:
print("Total Transactions :", len(df))

Total Transactions : 1310

In [ ]:
top_categories = (
    df[df["Type"] == "debit"]
      .groupby("category")["Amount"]
      .sum()
      .sort_values(ascending=False)
      .head(5)
)

print(top_categories)

Series([], Name: Amount, dtype: float64)

In [ ]:
top_vendors = (
    df[df["Type"] == "debit"]
      .groupby("vendor_clean")["Amount"]
      .sum()
      .sort_values(ascending=False)
      .head(5)
)

print(top_vendors)

Series([], Name: Amount, dtype: float64)

In [ ]:
print("=" * 60)
print("              SPENDDNA REPORT")
print("=" * 60)

print(f"Total Credits      : ₹{total_credits:,.2f}")
print(f"Total Debits       : ₹{total_debits:,.2f}")
print(f"Net Savings        : ₹{net_savings:,.2f}")
print(f"Savings Rate       : {savings_rate:.2f}%")
print(f"Transactions       : {len(df)}")
print(f"Unique Vendors     : {df['vendor_clean'].nunique()}")

print("\nTop 5 Categories")
print(top_categories)

print("\nTop 5 Vendors")
print(top_vendors)

print("=" * 60)

============================================================
              SPENDDNA REPORT
============================================================
Total Credits      : ₹0.00
Total Debits       : ₹0.00
Net Savings        : ₹0.00
Savings Rate       : nan%
Transactions       : 1310
Unique Vendors     : 38

Top 5 Categories
Series([], Name: Amount, dtype: float64)

Top 5 Vendors
Series([], Name: Amount, dtype: float64)
============================================================

In [ ]:
df["Month"] = df["Date"].dt.to_period("M")

In [ ]:
df[["Date", "Month"]].head()

        Date    Month
0 2024-01-01  2024-01
1        NaT      NaT
2        NaT      NaT
3 2024-01-01  2024-01
4        NaT      NaT

In [ ]:
monthly_spend = (
    df[df["Type"] == "debit"]
      .groupby("Month")["Amount"]
      .sum()
)

print(monthly_spend)

Series([], Freq: M, Name: Amount, dtype: float64)

In [ ]:
monthly_credit = (
    df[df["Type"] == "credit"]
      .groupby("Month")["Amount"]
      .sum()
)

print(monthly_credit)

Series([], Freq: M, Name: Amount, dtype: float64)

In [ ]:
monthly_summary = pd.DataFrame({
    "Credits": monthly_credit,
    "Debits": monthly_spend
}).fillna(0)

monthly_summary["Savings"] = (
    monthly_summary["Credits"] -
    monthly_summary["Debits"]
)

print(monthly_summary)

Empty DataFrame
Columns: [Credits, Debits, Savings]
Index: []

In [ ]:
print(df["Date"].dtype)

datetime64[ns]

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True, errors="coerce")

In [ ]:
print(df["Type"].value_counts())

Type
DR       662
Debit    642
CR         6
Name: count, dtype: int64

In [ ]:
df[df["Type"] == "debit"]

Empty DataFrame
Columns: [Date, Time, Description, Type, Amount, Balance, Mode, Ref, vendor_clean, category, Month]
Index: []

In [ ]:
df["Type"] = df["Type"].str.lower()

In [ ]:
print(df["Type"].value_counts())

Type
dr       662
debit    642
cr         6
Name: count, dtype: int64

In [ ]:
df["Month"] = df["Date"].dt.to_period("M")
print(df[["Date", "Month"]].head())

        Date    Month
0 2024-01-01  2024-01
1        NaT      NaT
2        NaT      NaT
3 2024-01-01  2024-01
4        NaT      NaT

In [ ]:
monthly_spend = (
    df[df["Type"] == "debit"]
    .groupby("Month")["Amount"]
    .sum()
)

print(monthly_spend)

Month
2024-01     8741.0
2024-02     3870.0
2024-03    21505.0
2024-04     4390.0
2024-05    19151.0
2024-06     5783.0
2024-07    18202.0
2024-08     5684.0
2024-09     1909.0
2024-10     2750.0
2024-11     2248.0
2024-12     2553.0
Freq: M, Name: Amount, dtype: float64

In [ ]:
print(df["Date"].dtype)

print(df["Type"].value_counts())

datetime64[ns]
Type
dr       662
debit    642
cr         6
Name: count, dtype: int64

In [ ]:
df["Category_Mean"] = (
    df.groupby("category")["Amount"]
      .transform("mean")
)

In [ ]:
df["Category_Std"] = (
    df.groupby("category")["Amount"]
      .transform("std")
)

In [ ]:
df["z_score"] = (
    (df["Amount"] - df["Category_Mean"])
    / df["Category_Std"]
)

In [ ]:
df[[
    "Description",
    "category",
    "Amount",
    "z_score"
]].head(10)

                        Description           category   Amount   z_score
0                AMAZON SELLER SVCS         E-Commerce   2462.0 -0.283441
1                         BHIM-BMTC             Others     50.0 -0.214195
2  NEFT-TECHCRUSH LABS-SALARY MAY24             Others  84728.0  7.990524
3              UPI-AMAN-8934@OKAXIS  Personal Transfer   1828.0  0.471266
4                      BHIM-BLINKIT             Others    270.0 -0.192878
5                        BHIM ZEPTO     Quick Commerce    625.0  0.716862
6            UPI-UBER-2426@HDFCBANK             Others    148.0 -0.204699
7                      BHIM-BLINKIT             Others    482.0 -0.172337
8              POS SWIGGY BANGALORE      Food Delivery    537.0  0.640844
9             UPI-GROWWPAY@HDFCBANK        Investments   3956.0 -1.271042

In [ ]:
anomalies = df[df["z_score"] > 3]

In [ ]:
print(anomalies[[
    "Date",
    "Description",
    "category",
    "Amount",
    "z_score"
]])

           Date                       Description    category   Amount  \
2           NaT  NEFT-TECHCRUSH LABS-SALARY MAY24      Others  84728.0
224         NaT  NEFT-TECHCRUSH LABS-SALARY MAY24      Others  84724.0
269         NaT            UPI-AMAZONPAY@HDFCBANK  E-Commerce  21986.0
438  2024-01-03  NEFT-TECHCRUSH LABS-SALARY MAY24      Others  84701.0
450         NaT                         AMAZON IN  E-Commerce  18273.0
475         NaT            UPI-AMAZONPAY@HDFCBANK  E-Commerce  19917.0
658         NaT  NEFT-TECHCRUSH LABS-SALARY MAY24      Others  84736.0
880  2024-01-05  NEFT-TECHCRUSH LABS-SALARY MAY24      Others  85393.0
1113        NaT  NEFT-TECHCRUSH LABS-SALARY MAY24      Others  85492.0
1298        NaT              AMAZONIN MARKETPLACE  E-Commerce  22008.0

       z_score
2     7.990524
224   7.990136
269   3.799180
438   7.987908
450   3.022763
475   3.366536
658   7.991299
880   8.054958
1113  8.064550
1298  3.803781

In [ ]:
anomalies = anomalies.sort_values(
    by="z_score",
    ascending=False
)

print(anomalies)

           Date   Time                       Description   Type   Amount  \
1113        NaT  09:31  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  85492.0
880  2024-01-05  09:37  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  85393.0
658         NaT  09:23  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  84736.0
2           NaT  09:35  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  84728.0
224         NaT  09:42  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  84724.0
438  2024-01-03  09:35  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  84701.0
1298        NaT  09:07              AMAZONIN MARKETPLACE     dr  22008.0
269         NaT  17:28            UPI-AMAZONPAY@HDFCBANK  debit  21986.0
475         NaT  21:33            UPI-AMAZONPAY@HDFCBANK  debit  19917.0
450         NaT  11:58                         AMAZON IN  debit  18273.0

       Balance  Mode        Ref vendor_clean    category    Month  \
1113  720079.0  NEFT  TXN399607       Salary      Others      NaT
880   671166.0  NEFT  TXN820221       Salary      Others  2024-01
658   623971.0  NEFT  TXN395442       Salary      Others      NaT
2     484728.0  NEFT  TXN246316       Salary      Others      NaT
224   530245.0  NEFT  TXN542666       Salary      Others      NaT
438   576808.0  NEFT  TXN214576       Salary      Others  2024-01
1298 -699028.0   UPI  TXN313051       Amazon  E-Commerce      NaT
269  -360151.0   UPI  TXN988380       Amazon  E-Commerce      NaT
475  -465439.0   UPI  TXN674071       Amazon  E-Commerce      NaT
450  -558650.0   UPI  TXN228115       Amazon  E-Commerce      NaT

      Category_Mean  Category_Std   z_score
1113    2260.627119  10320.646887  8.064550
880     2260.627119  10320.646887  8.054958
658     2260.627119  10320.646887  7.991299
2       2260.627119  10320.646887  7.990524
224     2260.627119  10320.646887  7.990136
438     2260.627119  10320.646887  7.987908
1298    3817.476510   4782.221967  3.803781
269     3817.476510   4782.221967  3.799180
475     3817.476510   4782.221967  3.366536
450     3817.476510   4782.221967  3.022763

In [ ]:
print(anomalies.head(10))

           Date   Time                       Description   Type   Amount  \
1113        NaT  09:31  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  85492.0
880  2024-01-05  09:37  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  85393.0
658         NaT  09:23  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  84736.0
2           NaT  09:35  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  84728.0
224         NaT  09:42  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  84724.0
438  2024-01-03  09:35  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  84701.0
1298        NaT  09:07              AMAZONIN MARKETPLACE     dr  22008.0
269         NaT  17:28            UPI-AMAZONPAY@HDFCBANK  debit  21986.0
475         NaT  21:33            UPI-AMAZONPAY@HDFCBANK  debit  19917.0
450         NaT  11:58                         AMAZON IN  debit  18273.0

       Balance  Mode        Ref vendor_clean    category    Month  \
1113  720079.0  NEFT  TXN399607       Salary      Others      NaT
880   671166.0  NEFT  TXN820221       Salary      Others  2024-01
658   623971.0  NEFT  TXN395442       Salary      Others      NaT
2     484728.0  NEFT  TXN246316       Salary      Others      NaT
224   530245.0  NEFT  TXN542666       Salary      Others      NaT
438   576808.0  NEFT  TXN214576       Salary      Others  2024-01
1298 -699028.0   UPI  TXN313051       Amazon  E-Commerce      NaT
269  -360151.0   UPI  TXN988380       Amazon  E-Commerce      NaT
475  -465439.0   UPI  TXN674071       Amazon  E-Commerce      NaT
450  -558650.0   UPI  TXN228115       Amazon  E-Commerce      NaT

      Category_Mean  Category_Std   z_score
1113    2260.627119  10320.646887  8.064550
880     2260.627119  10320.646887  8.054958
658     2260.627119  10320.646887  7.991299
2       2260.627119  10320.646887  7.990524
224     2260.627119  10320.646887  7.990136
438     2260.627119  10320.646887  7.987908
1298    3817.476510   4782.221967  3.803781
269     3817.476510   4782.221967  3.799180
475     3817.476510   4782.221967  3.366536
450     3817.476510   4782.221967  3.022763

In [ ]:
print("Total Anomalies:", len(anomalies))

Total Anomalies: 10

In [ ]:
largest_transactions = (
    df.groupby("category")
      .apply(lambda x: x.nlargest(1, "Amount"))
)

print(largest_transactions[[
    "category",
    "Description",
    "Amount"
]])

                                 category                       Description  \
category
Cafe              608                Cafe                    TATA STARBUCKS
Cash Withdrawal   311     Cash Withdrawal                 ATM-WDL-HDFC-4942
E-Commerce        1298         E-Commerce              AMAZONIN MARKETPLACE
Entertainment     727       Entertainment             BIGTREE ENTERTAINMENT
Food Delivery     1207      Food Delivery       UPI-SWIGGY-INSTAMART@OKAXIS
Fuel              541                Fuel          POS INDIAN OIL BANGALORE
Investments       50          Investments             UPI-ZERODHA-COIN@AXIS
Others            1113             Others  NEFT-TECHCRUSH LABS-SALARY MAY24
Personal Transfer 1098  Personal Transfer             UPI-ANKIT-5946@OKAXIS
Quick Commerce    21       Quick Commerce                 GROFERS INDIA P L
Subscriptions     357       Subscriptions                STAR INDIA PVT LTD
Transport         403           Transport              UPI-OLACABS@HDFCBANK
Utilities         785           Utilities          UPI-BESCOM-BILL@HDFCBANK

                         Amount
category
Cafe              608     479.0
Cash Withdrawal   311    5000.0
E-Commerce        1298  22008.0
Entertainment     727    1046.0
Food Delivery     1207    833.0
Fuel              541   10505.0
Investments       50    15000.0
Others            1113  85492.0
Personal Transfer 1098   2548.0
Quick Commerce    21      878.0
Subscriptions     357    1272.0
Transport         403     480.0
Utilities         785    2394.0

/tmp/ipykernel_358/3448437300.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.nlargest(1, "Amount"))

In [ ]:
print("=" * 60)
print("        FEATURE 7 - ANOMALY REPORT")
print("=" * 60)

print("Total Anomalies :", len(anomalies))

print("\nTop 10 Anomalies")
print(anomalies[[
    "Description",
    "category",
    "Amount",
    "z_score"
]].head(10))

print("=" * 60)

============================================================
        FEATURE 7 - ANOMALY REPORT
============================================================
Total Anomalies : 10

Top 10 Anomalies
                           Description    category   Amount   z_score
1113  NEFT-TECHCRUSH LABS-SALARY MAY24      Others  85492.0  8.064550
880   NEFT-TECHCRUSH LABS-SALARY MAY24      Others  85393.0  8.054958
658   NEFT-TECHCRUSH LABS-SALARY MAY24      Others  84736.0  7.991299
2     NEFT-TECHCRUSH LABS-SALARY MAY24      Others  84728.0  7.990524
224   NEFT-TECHCRUSH LABS-SALARY MAY24      Others  84724.0  7.990136
438   NEFT-TECHCRUSH LABS-SALARY MAY24      Others  84701.0  7.987908
1298              AMAZONIN MARKETPLACE  E-Commerce  22008.0  3.803781
269             UPI-AMAZONPAY@HDFCBANK  E-Commerce  21986.0  3.799180
475             UPI-AMAZONPAY@HDFCBANK  E-Commerce  19917.0  3.366536
450                          AMAZON IN  E-Commerce  18273.0  3.022763
============================================================

In [ ]:
total_spend = df[df["Type"]=="debit"]["Amount"].sum()

In [ ]:
category_spend = (
    df[df["Type"]=="debit"]
    .groupby("category")["Amount"]
    .sum()
)

In [ ]:
category_percent = (
    category_spend / total_spend * 100
).round(2)

print(category_percent)

category
Cafe                  1.27
Cash Withdrawal       2.86
E-Commerce           32.99
Entertainment         0.27
Food Delivery         8.68
Fuel                  3.04
Investments          14.62
Others               28.31
Personal Transfer     1.28
Quick Commerce        2.62
Subscriptions         0.37
Transport             1.69
Utilities             2.00
Name: Amount, dtype: float64

In [ ]:
archetypes = []

In [ ]:
food_percent = category_percent.get("Food Delivery",0)

if food_percent >= 25:
    archetypes.append(
        f"THE FOODIE ({food_percent:.1f}% on Food Delivery)"
    )

In [ ]:
quick_percent = category_percent.get("Quick Commerce",0)

if quick_percent >= 15:
    archetypes.append(
        f"THE QUICK COMMERCE ({quick_percent:.1f}% on Quick Commerce)"
    )

In [ ]:
shop_percent = category_percent.get("E-Commerce",0)

if shop_percent >= 15:
    archetypes.append(
        f"THE SHOPAHOLIC ({shop_percent:.1f}% on E-Commerce)"
    )

In [ ]:
invest_percent = category_percent.get("Investments",0)

if invest_percent >= 10:
    archetypes.append(
        f"THE INVESTOR ({invest_percent:.1f}% on Investments)"
    )

In [ ]:
print(df.columns.tolist())

['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode', 'Ref', 'vendor_clean', 'category', 'Month', 'Category_Mean', 'Category_Std', 'z_score']

In [ ]:
print(df.head())

        Date   Time                       Description   Type   Amount  \
0 2024-01-01  03:11                AMAZON SELLER SVCS  debit   2462.0
1        NaT  05:44                         BHIM-BMTC     dr     50.0
2        NaT  09:35  NEFT-TECHCRUSH LABS-SALARY MAY24     cr  84728.0
3 2024-01-01  14:07              UPI-AMAN-8934@OKAXIS  debit   1828.0
4        NaT  14:23                      BHIM-BLINKIT  debit    270.0

    Balance  Mode        Ref   vendor_clean           category    Month  \
0  678275.0   UPI  TXN190872         Amazon         E-Commerce  2024-01
1  681007.0   UPI  TXN143064           BMTC             Others      NaT
2  484728.0  NEFT  TXN246316         Salary             Others      NaT
3 -748745.0   UPI  TXN569226   P2P Transfer  Personal Transfer  2024-01
4  680737.0   UPI  TXN968962  Uncategorised             Others      NaT

   Category_Mean  Category_Std   z_score
0    3817.476510   4782.221967 -0.283441
1    2260.627119  10320.646887 -0.214195
2    2260.627119  10320.646887  7.990524
3    1417.071429    871.968283  0.471266
4    2260.627119  10320.646887 -0.192878

In [ ]:
df["Hour"] = df["Time"].astype(str).str[:2].astype(int)

In [ ]:
print(df[["Time", "Hour"]].head())

    Time  Hour
0  03:11     3
1  05:44     5
2  09:35     9
3  14:07    14
4  14:23    14

In [ ]:
print(df.columns.tolist())

['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode', 'Ref', 'vendor_clean', 'category', 'Month', 'Category_Mean', 'Category_Std', 'z_score', 'Hour']

In [ ]:
print("="*60)
print("SPENDING ARCHETYPES")
print("="*60)

for a in archetypes:
    print("->", a)

============================================================
SPENDING ARCHETYPES
============================================================
-> THE SHOPAHOLIC (33.0% on E-Commerce)
-> THE INVESTOR (14.6% on Investments)

In [ ]:
print("="*70)
print("                 SPENDDNA FINAL REPORT")
print("="*70)

print(f"Total Credits     : ₹{total_credits:,.2f}")
print(f"Total Debits      : ₹{total_debits:,.2f}")
print(f"Net Savings       : ₹{net_savings:,.2f}")
print(f"Savings Rate      : {savings_rate:.2f}%")

print("\nTop Categories")
print(category_percent)

print("\nTop Vendors")
print(top_vendors)

print("\nSPENDING ARCHETYPES")
for a in archetypes:
    print("->", a)

print("="*70)

======================================================================
                 SPENDDNA FINAL REPORT
======================================================================
Total Credits     : ₹0.00
Total Debits      : ₹0.00
Net Savings       : ₹0.00
Savings Rate      : nan%

Top Categories
category
Cafe                  1.27
Cash Withdrawal       2.86
E-Commerce           32.99
Entertainment         0.27
Food Delivery         8.68
Fuel                  3.04
Investments          14.62
Others               28.31
Personal Transfer     1.28
Quick Commerce        2.62
Subscriptions         0.37
Transport             1.69
Utilities             2.00
Name: Amount, dtype: float64

Top Vendors
Series([], Name: Amount, dtype: float64)

SPENDING ARCHETYPES
-> THE SHOPAHOLIC (33.0% on E-Commerce)
-> THE INVESTOR (14.6% on Investments)
======================================================================

In [ ]:
df.to_csv("SpendDNA_Final.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

In [ ]:
anomalies.to_csv("Anomalies.csv", index=False)

print("Anomaly report saved!")

Anomaly report saved!

In [ ]:
monthly_summary.to_csv("Monthly_Summary.csv", index=True)

print("Monthly summary saved!")

Monthly summary saved!

In [ ]:
print("="*60)
print("SPENDDNA PROJECT SUMMARY")
print("="*60)

print("Transactions :", len(df))
print("Unique Vendors :", df["vendor_clean"].nunique())
print("Categories :", df["category"].nunique())
print("Anomalies :", len(anomalies))

print("="*60)

============================================================
SPENDDNA PROJECT SUMMARY
============================================================
Transactions : 1310
Unique Vendors : 38
Categories : 13
Anomalies : 10
============================================================

In [119]:
print(df["Type"].value_counts())

Type
dr       662
debit    642
cr         6
Name: count, dtype: int64

In [120]:
df["Type"] = df["Type"].str.strip().str.lower()

In [121]:
print(df["Type"].value_counts())

Type
dr       662
debit    642
cr         6
Name: count, dtype: int64

In [122]:
total_credits = df[df["Type"]=="credit"]["Amount"].sum()
total_debits = df[df["Type"]=="debit"]["Amount"].sum()

net_savings = total_credits - total_debits

if total_credits > 0:
    savings_rate = (net_savings / total_credits) * 100
else:
    savings_rate = 0

print(total_credits)
print(total_debits)

0.0
857855.0

In [123]:
top_vendors = (
    df[df["Type"]=="debit"]
    .groupby("vendor_clean")["Amount"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

print(top_vendors)

vendor_clean
Amazon        178105.0
Zerodha       105000.0
Rent           90000.0
Flipkart       64922.0
Restaurant     59454.0
Name: Amount, dtype: float64

In [124]:
df[df["Type"] == "debit"]

,Date,Time,Description,Type,Amount,Balance,Mode,Ref,vendor_clean,category,Month,Category_Mean,Category_Std,z_score,Hour
0,2024-01-01,03:11,AMAZON SELLER SVCS,debit,2462.0,678275.0,UPI,TXN190872,Amazon,E-Commerce,2024-01,3817.476510,4782.221967,-0.283441,3
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,debit,1828.0,-748745.0,UPI,TXN569226,P2P Transfer,Personal Transfer,2024-01,1417.071429,871.968283,0.471266,14
4,NaT,14:23,BHIM-BLINKIT,debit,270.0,680737.0,UPI,TXN968962,Uncategorised,Others,NaT,2260.627119,10320.646887,-0.192878,14
6,2024-01-01,14:50,UPI-UBER-2426@HDFCBANK,debit,148.0,677020.0,UPI,TXN546173,Uncategorised,Others,2024-01,2260.627119,10320.646887,-0.204699,14
7,NaT,21:44,BHIM-BLINKIT,debit,482.0,677168.0,UPI,TXN599219,Uncategorised,Others,NaT,2260.627119,10320.646887,-0.172337,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1311,NaT,12:31,Swiggy*Order,debit,376.0,-306640.0,UPI,TXN823420,Swiggy,Food Delivery,NaT,438.485465,153.726234,-0.406472,12
1314,NaT,21:54,BLINKIT BANGALORE,debit,878.0,-305746.0,UPI,TXN974187,Uncategorised,Others,NaT,2260.627119,10320.646887,-0.133967,21
1315,NaT,00:12,UPI-OLACABS@HDFCBANK,debit,215.0,-307614.0,UPI,TXN802374,Ola,Transport,NaT,280.910891,110.997757,-0.593804,0
1318,NaT,16:39,UPI-RAPIDO@OKAXIS,debit,170.0,-307399.0,UPI,TXN540114,Uncategorised,Others,NaT,2260.627119,10320.646887,-0.202567,16
1319,NaT,18:36,POS BANGALORE RESTAURANT,debit,1030.0,-308644.0,UPI,TXN658352,Restaurant,Others,NaT,2260.627119,10320.646887,-0.119239,18

In [125]:
print(df["Type"].value_counts())

Type
dr       662
debit    642
cr         6
Name: count, dtype: int64

In [126]:
from google.colab import files

files.download("SpendDNA_Final.csv")
files.download("Anomalies.csv")
files.download("Monthly_Summary.csv")

In [128]:
print("="*72)
print("                 SpendDNA REPORT - AKSHAYA AYODHYA")
print("          6 Months | 1,310 Transactions | Jan - Jun 2024")
print("="*72)

print("\nEXECUTIVE SUMMARY")
print(f"  Total Credits   : ₹{total_credits:,.2f}")
print(f"  Total Debits    : ₹{total_debits:,.2f}")
print(f"  Net Savings     : ₹{net_savings:,.2f}")
print(f"  Savings Rate    : {savings_rate:.2f}%")
print(f"  Transactions    : {len(df)}")
print(f"  Unique Vendors  : {df['vendor_clean'].nunique()}")

print("\n" + "="*72)
print("TOP CATEGORIES (% of Total Debit)")
print("="*72)

category_amount = (
    df[df["Type"]=="debit"]
    .groupby("category")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

for cat, amt in category_amount.head(5).items():
    pct = (amt/total_debits)*100 if total_debits > 0 else 0
    bar = "#" * int(pct/2)
    print(f"{cat:<18} {bar:<20} {pct:5.1f}%   ₹{amt:,.0f}")

print("\n" + "="*72)
print("TOP VENDORS")
print("="*72)

vendor_amount = (
    df[df["Type"]=="debit"]
    .groupby("vendor_clean")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

vendor_orders = (
    df[df["Type"]=="debit"]
    .groupby("vendor_clean")
    .size()
)

for vendor in vendor_amount.head(5).index:
    print(f"{vendor:<18} ₹{vendor_amount[vendor]:>10,.0f} ({vendor_orders[vendor]} transactions)")

print("\n" + "="*72)
print("MONTHLY TREND")
print("="*72)

monthly = (
    df[df["Type"]=="debit"]
    .groupby(df["Date"].dt.strftime("%b"))["Amount"]
    .sum()
)

for month, value in monthly.items():
    bar = "#" * int(value/monthly.max()*15)
    print(f"{month:<5} ₹{value:>10,.0f} {bar}")

print("\n" + "="*72)
print("TOP ANOMALIES")
print("="*72)

display_cols = ["Date","vendor_clean","category","Amount","z_score"]

print(anomalies[display_cols].head(5).to_string(index=False))

print("\n" + "="*72)
print("SPENDING ARCHETYPES")
print("="*72)

if archetypes:
    for a in archetypes:
        print("->", a)
else:
    print("No archetypes detected.")

print("\n" + "="*72)
print("KEY INSIGHTS")
print("="*72)

print(f"1. Total debit spending is ₹{total_debits:,.0f}.")
print(f"2. Highest spending category: {category_amount.idxmax()}.")
print(f"3. Highest spending vendor: {vendor_amount.idxmax()}.")
print(f"4. Total anomalies detected: {len(anomalies)}.")
print(f"5. Total savings: ₹{net_savings:,.0f}.")
print("="*72)

========================================================================
                 SpendDNA REPORT - AKSHAYA AYODHYA
          6 Months | 1,310 Transactions | Jan - Jun 2024
========================================================================

EXECUTIVE SUMMARY
  Total Credits   : ₹0.00
  Total Debits    : ₹857,855.00
  Net Savings     : ₹-857,855.00
  Savings Rate    : 0.00%
  Transactions    : 1310
  Unique Vendors  : 38

========================================================================
TOP CATEGORIES (% of Total Debit)
========================================================================
E-Commerce         ################      33.0%   ₹283,024
Others             ##############        28.3%   ₹242,818
Investments        #######               14.6%   ₹125,456
Food Delivery      ####                   8.7%   ₹74,440
Fuel               #                      3.0%   ₹26,073

========================================================================
TOP VENDORS
========================================================================
Amazon             ₹   178,105 (47 transactions)
Zerodha            ₹   105,000 (7 transactions)
Rent               ₹    90,000 (5 transactions)
Flipkart           ₹    64,922 (18 transactions)
Restaurant         ₹    59,454 (38 transactions)

========================================================================
MONTHLY TREND
========================================================================
Apr   ₹     4,390 ###
Aug   ₹     5,684 ###
Dec   ₹     2,553 #
Feb   ₹     3,870 ##
Jan   ₹     8,741 ######
Jul   ₹    18,202 ############
Jun   ₹     5,783 ####
Mar   ₹    21,505 ###############
May   ₹    19,151 #############
Nov   ₹     2,248 #
Oct   ₹     2,750 #
Sep   ₹     1,909 #

========================================================================
TOP ANOMALIES
========================================================================
      Date vendor_clean category  Amount  z_score
       NaT       Salary   Others 85492.0 8.064550
2024-01-05       Salary   Others 85393.0 8.054958
       NaT       Salary   Others 84736.0 7.991299
       NaT       Salary   Others 84728.0 7.990524
       NaT       Salary   Others 84724.0 7.990136

========================================================================
SPENDING ARCHETYPES
========================================================================
-> THE SHOPAHOLIC (33.0% on E-Commerce)
-> THE INVESTOR (14.6% on Investments)

========================================================================
KEY INSIGHTS
========================================================================
1. Total debit spending is ₹857,855.
2. Highest spending category: E-Commerce.
3. Highest spending vendor: Amazon.
4. Total anomalies detected: 10.
5. Total savings: ₹-857,855.
========================================================================